/**
******************************************************************************
* Xenia : Xbox 360 Emulator Research Project                                 *
******************************************************************************
* Copyright 2023 Ben Vanik. All rights reserved.                             *
* Released under the BSD license - see LICENSE in the root for more details. *
******************************************************************************
*/

#include "main_gnulinux.h"
#include <filesystem>
#include <fstream>
#include <regex>
#include "cvar.h"
#include "logging.h"

// Autogenerated by `xb premake`.
#include "build/version.h"

namespace xe {
  int InitializeGNULinuxApp(const std::string_view app_name) {
    // Initialize logging. Needs parsed FLAGS.
    xe::InitializeLogging(app_name);

    // Print version info.
    XELOGI(
        "Build: "
    #ifdef XE_BUILD_IS_PR
        "PR#" XE_BUILD_PR_NUMBER " " XE_BUILD_PR_REPO " " XE_BUILD_PR_BRANCH
        "@" XE_BUILD_PR_COMMIT_SHORT " against "
    #endif
        XE_BUILD_BRANCH "@" XE_BUILD_COMMIT_SHORT " on " XE_BUILD_DATE);

    return 0;
  }

  void ShutdownGNULinuxApp() {
    xe::ShutdownLogging();
  }
}