/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2025 Xenia Canary. All rights reserved.                          *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#include "xenia/app/emulator_window.h"
#include "xenia/app/recently_played_content_dialog.h"

#include <filesystem>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <utility>

#include "third_party/imgui/imgui.h"
#include "third_party/stb/stb_image_write.h"
#include "third_party/tomlplusplus/toml.hpp"
#include "xenia/base/assert.h"
#include "xenia/base/clock.h"
#include "xenia/base/cvar.h"
#include "xenia/base/debugging.h"
#include "xenia/base/logging.h"
#include "xenia/base/platform.h"
#include "xenia/base/profiling.h"
#include "xenia/base/system.h"
#include "xenia/base/threading.h"
#include "xenia/cpu/processor.h"
#include "xenia/emulator.h"
#include "xenia/gpu/command_processor.h"
#include "xenia/gpu/graphics_system.h"
#include "xenia/hid/input_system.h"
#include "xenia/kernel/xam/profile_manager.h"
#include "xenia/kernel/xam/xam_module.h"
#include "xenia/kernel/xam/xam_state.h"
#include "xenia/ui/file_picker.h"
#include "xenia/ui/graphics_provider.h"
#include "xenia/ui/imgui_dialog.h"
#include "xenia/ui/imgui_drawer.h"
#include "xenia/ui/imgui_host_notification.h"
#include "xenia/ui/immediate_drawer.h"
#include "xenia/ui/presenter.h"
#include "xenia/ui/ui_event.h"
#include "xenia/ui/virtual_key.h"

// Autogenerated by `xb premake`.
#include "build/version.h"

namespace xe {
namespace kernel {
namespace xam {
extern std::atomic<int> xam_dialogs_shown_;
}
}  // namespace kernel
}  // namespace xe

namespace xe {
namespace app {

MainMenuWindow::MainMenuWindow(ui::ImGuiDrawer* imgui_drawer,
                               EmulatorWindow* emulator_window)
    : ui::ImGuiDialog(imgui_drawer), emulator_window_(emulator_window) {
  std::function<void(uint8_t)> f = std::bind(
      &MainMenuWindow::OnGuideButtonPress, this, std::placeholders::_1);
  imgui_drawer->SetGuideButtonAction(f);

  currently_selected_submenu_ = std::make_unique<RecentlyPlayedContentDialog>(
      imgui_drawer, emulator_window);
}

MainMenuWindow::~MainMenuWindow() { XELOGE("WAIT"); }

void MainMenuWindow::OnGuideButtonPress(uint8_t controller_index) {
  controller_index_ = controller_index;
  is_visible_ ^= true;
}

void MainMenuWindow::DrawXeniaInfo() {
  // TODO: Add proper Xenia icon
  ImGui::Image(reinterpret_cast<ImTextureID>(
                   emulator_window_->imgui_drawer()->GetNotificationIcon(0)),
               ui::default_image_icon_size);
  ImGui::SameLine();

  if (ImGui::BeginTable("XeniaInfoTable", 1)) {
    // Row 0 - Base name
    ImGui::TableNextRow();
    ImGui::TableSetColumnIndex(0);

    ImGui::PushFont(emulator_window_->imgui_drawer()->GetTitleFont());
    ImGui::Text("Xenia Canary");
    ImGui::PopFont();

    // Some padding between name and remaining entries
    ImGui::Dummy(ImVec2(5.f, 5.f));
    // Row 1 - Commit
    ImGui::TableNextRow();
    ImGui::TableSetColumnIndex(0);

    ImGui::Text("Build: %s", XE_BUILD_COMMIT_SHORT);

    // Row 2 - Time
    ImGui::TableNextRow();
    ImGui::TableSetColumnIndex(0);

    ImGui::Text("Build date: %s", XE_BUILD_DATE);
  }

  ImGui::EndTable();
}

void MainMenuWindow::OnDraw(ImGuiIO& io) {
  if (!is_visible_) {
    ImGui::SetNextWindowCollapsed(true, ImGuiCond_Always);
    // return;
  }

  if (!has_opened_) {
    ImGui::OpenPopup("Main Menu");
    has_opened_ = true;
  }

  ImGuiViewport* viewport = ImGui::GetMainViewport();
  ImGui::SetNextWindowPos(viewport->Pos);
  ImGui::SetNextWindowSize(viewport->Size);

  bool dialog_open = true;
  if (!ImGui::BeginPopupModal("Main Menu", &dialog_open,
                              ImGuiWindowFlags_NoDecoration)) {
    Close();
    return;
  }

  const float sidebar_size = ImGui::GetContentRegionAvail().x * 0.2f;
  const float content_size = ImGui::GetContentRegionAvail().x - sidebar_size;

  DrawSidebarMenu(sidebar_size);
  ImGui::SameLine();
  DrawContentView(content_size);

  ImGui::End();
}

void MainMenuWindow::DrawSidebarMenu(const float width) {
  const float button_height = 60.f;

  ImGui::BeginChild(
      "MainMenuSidebar", ImVec2(width, 0),
      ImGuiChildFlags_NavFlattened | ImGuiChildFlags_AutoResizeX,
      ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse);

  DrawXeniaInfo();
  ImGui::Separator();

  if (!was_cursor_set_) {
    ImGui::SetKeyboardFocusHere();
    // ImGui::SetItemDefaultFocus();
    was_cursor_set_ = true;
  }

  ImGui::Dummy(ImVec2(10.f, 10.f));

  ImGui::PushFont(emulator_window_->imgui_drawer()->GetTitleFont());

  if (ImGui::Button("Open Recent", ImVec2(width * 0.90f, button_height))) {
    current_content_ = MainMenuUiContent::recent;
    currently_selected_submenu_ = std::make_unique<RecentlyPlayedContentDialog>(
        imgui_drawer(), emulator_window_);
  }

  if (ImGui::Button("Open", ImVec2(width * 0.90f, button_height))) {
    currently_selected_submenu_.reset();
  }

  if (ImGui::Button("Install", ImVec2(width * 0.90f, button_height))) {
    currently_selected_submenu_.reset();
  }

  if (ImGui::Button("Profiles", ImVec2(width * 0.90f, button_height))) {
    current_content_ = MainMenuUiContent::profiles;
    currently_selected_submenu_.reset();
  }

  if (ImGui::Button("Settings", ImVec2(width * 0.90f, button_height))) {
    current_content_ = MainMenuUiContent::settings;
    currently_selected_submenu_.reset();
  }

  if (ImGui::Button("About", ImVec2(width * 0.90f, button_height))) {
    current_content_ = MainMenuUiContent::about;
    currently_selected_submenu_.reset();
  }

  ImGui::PopFont();
  ImGui::Separator();

  ImGui::Dummy(ImVec2(150.f, 150.f));

  DrawCurrentlySignedProfile();

  ImGui::EndChild();
}

void MainMenuWindow::DrawContentView(const float width) {
  ImGui::BeginChild("MainMenuContent", ImVec2(width, 0), true);

  if (currently_selected_submenu_) {
    currently_selected_submenu_->Draw();
  }

  switch (current_content_) {
    case MainMenuUiContent::recent:
      // DrawRecentMenu();
      break;
    case MainMenuUiContent::profiles:
      DrawProfilesMenu();
      break;
    case MainMenuUiContent::settings:
      DrawSettings();
      break;
    case MainMenuUiContent::about:
      DrawAbout();
      break;
    default:
      // DrawRecentMenu();
      break;
  }

  ImGui::EndChild();
}

void MainMenuWindow::DrawCurrentlySignedProfile() {
  if (emulator_window_ && emulator_window_->emulator()->kernel_state()) {
    const auto profile = emulator_window_->emulator()
                             ->kernel_state()
                             ->xam_state()
                             ->profile_manager()
                             ->GetProfile(controller_index_);

    if (profile) {
      const auto icon = emulator_window_->imgui_drawer()->GetNotificationIcon(
          controller_index_);

      if (icon && controller_index_ < XUserMaxUserCount) {
        ImGui::Image(reinterpret_cast<ImTextureID>(icon),
                     ui::default_image_icon_size);
      } else {
        ImGui::Dummy(ui::default_image_icon_size);
      }

      ImGui::SameLine();

      ImGui::BeginGroup();
      ImGui::Text("%s", profile->name().c_str());
      ImGui::Text("Profile XUID: %s",
                  fmt::format("{:016X}", profile->xuid()).c_str());
      ImGui::Text("Signed into slot: %i", controller_index_ + 1);
      ImGui::EndGroup();
    }
  } else {
    ImGui::Button("Sign-in");
  }
}

/*
void MainMenuWindow::DrawRecentMenu() {
    ImGui::Text("Lately played titles");

    const auto recent_titles = emulator_window_->GetRecentlyPlayedTitles();


    ImGui::BeginTable("RecentTable", 5);

    ImGui::TableSetupColumn("ID");
    ImGui::TableSetupColumn("Image");
    ImGui::TableSetupColumn("Title Name");
    ImGui::TableSetupColumn("Path");
    ImGui::TableSetupColumn("Last Played");
    ImGui::TableHeadersRow();

    if (!ImGui::IsItemFocused()) {
      //ImGui::SetKeyboardFocusHere();
    }
    uint8_t index = 1;
    for (const auto& entry : *recent_titles) {
      //ImGui::BeginChild(index);
      ImGui::TableNextColumn();

      if(ImGui::Selectable(entry.title_name.c_str(), selected_recently_title_,
                            ImGuiSelectableFlags_SpanAllColumns)) {
        emulator_window_->RunTitle(entry.path_to_file);
      }

      //ImGui::Text("%i", index++);
      ImGui::TableNextColumn();
      ImGui::Dummy(ImVec2(75.f, 75.f));
      ImGui::TableNextColumn();
      ImGui::Text(fmt::format("{}", entry.title_name).c_str());
      ImGui::TableNextColumn();
      ImGui::Text(fmt::format("{}", entry.path_to_file).c_str());
      ImGui::TableNextColumn();
      ImGui::Text("Unknown");

      //ImGui::EndChild();
      ImGui::TableNextRow();

    }

    ImGui::EndTable();
}*/

void MainMenuWindow::DrawProfilesMenu() {
  ImGui::TextWrapped(
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed porta a "
      "odio ut dictum. Cras pretium mauris a eros vestibulum ultricies. "
      "Suspendisse dictum justo ut est gravida, rutrum tempor turpis "
      "vulputate. Vivamus vulputate orci elit, at pharetra massa dignissim in. "
      "Nulla metus eros, imperdiet id iaculis quis, aliquam non neque. Duis a "
      "nisl sit amet nunc maximus vehicula. Proin ac tellus id nibh varius "
      "eleifend. Maecenas id aliquam sapien. Phasellus dapibus diam in nunc "
      "volutpat convallis. Maecenas nisl lacus, malesuada eu neque in, "
      "imperdiet sollicitudin enim.");

  ImGui::TextWrapped(
      "Vestibulum lorem mauris, finibus eu dui id, mattis elementum arcu. "
      "Praesent elementum faucibus mauris. Ut nisi sem, eleifend ut turpis "
      "sed, varius mattis leo. Phasellus sagittis lorem sit amet ligula "
      "consectetur rhoncus. In quis velit fermentum, pharetra tortor sit amet, "
      "eleifend ligula. Pellentesque a aliquet lectus, in tincidunt magna. "
      "Morbi viverra dolor in felis mattis, quis interdum quam viverra. "
      "Quisque blandit, ante quis sodales consectetur, magna leo lobortis "
      "sapien, non venenatis justo ante quis diam. Suspendisse posuere leo eu "
      "turpis convallis, tincidunt fermentum nisl vulputate. Suspendisse "
      "fermentum in orci eget dictum. Integer blandit ultricies nunc, et "
      "volutpat massa ultrices id. Nunc eget dui sit amet nunc interdum "
      "accumsan vel hendrerit leo. Donec lobortis eu odio quis mollis.");
}
void MainMenuWindow::DrawSettings() {}
void MainMenuWindow::DrawAbout() {}

}  // namespace app
}  // namespace xe
