plugins {
    id 'com.android.application'
}

android {
    archivesBaseName = 'AetherX360'
    compileSdkVersion 33
    ndkVersion '25.0.8775105'

    defaultConfig {
        applicationId 'jp.xenia.emulator'
        // 24 (7.0) - Vulkan.
        minSdkVersion 24
        targetSdkVersion 33
        versionCode 1
        versionName 'Prototype'
        ndk {
            abiFilters 'arm64-v8a', 'x86_64'
            stl 'c++_static'
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix '.debug'
            debuggable true
        }
        checked {
            applicationIdSuffix '.checked'
            debuggable true
        }
    }

    flavorDimensions 'distribution'
    productFlavors {
        github {
            dimension 'distribution'
            applicationIdSuffix '.github'
        }
        googlePlay {
            dimension 'distribution'
            // TODO(Triang3l): Provide a signing config for core contributors only.
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'org.jetbrains:annotations:15.0'
}