/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

// VK_EXT_metal_surface (#218).
XE_UI_VULKAN_FUNCTION(vkCreateMetalSurfaceEXT)
